In [8]:
L=[1,2,3]
L.insert(1,2)

In [9]:
print(L)

[1, 2, 2, 3]


In [11]:
help(L)

Help on list object:

class list(object)
 |  list() -> new empty list
 |  list(iterable) -> new list initialized from iterable's items
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /

In [11]:
def sum(a,b):
    """sums two parameters"""
    return a + b
sum?

    

In [16]:
sum??


In [17]:
L.

SyntaxError: invalid syntax (<ipython-input-17-749de8a9b36a>, line 1)

In [18]:
from iterools import %colors


SyntaxError: invalid syntax (<ipython-input-18-6e0eb6641a1d>, line 1)

In [19]:
import pandas as pd

In [22]:
*Warning?

ERROR:root:Line magic function `%paste` not found.


TypeError: 'int' object is not iterable

In [4]:
%paste


ERROR:root:Line magic function `%paste` not found.


In [6]:
print("hello world")

hello world


In [8]:
%%timeit 
for x in range(1000):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386


891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
16

421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670


800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69


278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527


882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
15

356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605


885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
16

411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660


891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
16

339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588


829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
10

546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795


382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631


879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
15

398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647


903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
18

555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804


389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638


25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293

886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
16

449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698


396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645


920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
19

877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
15

585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834


417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666


389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638


44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307


In [9]:
%timeit?


In [13]:
sum?

In [14]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%py

In [29]:
%magic


In [30]:
print(In)

['', "get_ipython().magic('run test.py')", "get_ipython().magic('run test.py')", 'print("hallO")', "get_ipython().magic('timeit sum(1000+1000)')", "get_ipython().magic('timeit for x in range(1000):')\n    print(x)", "get_ipython().magic('timeit')\nfor x in range(1000):\n    print(x)", "get_ipython().run_cell_magic('|timeit', '', 'for x in range(1000):\\n    print(x)')", "get_ipython().run_cell_magic('timeit', '', 'for x in range(1000):\\n    print(x)')", "get_ipython().magic('pinfo %timeit')", "get_ipython().magic('pinfo sum')", 'def sum(a,b):\n    """sums two parameters"""\n    return a + b\nget_ipython().magic(\'pinfo sum\')\n\n    ', "get_ipython().magic('pinfo sum')", "get_ipython().magic('pinfo sum')", "get_ipython().magic('lsmagic')", 'get_ipython().run_cell_magic(\'HTML\', \'\', \'print("<h3>Hallo</h3>")\')', 'print(%html"<h3>hallo</h3>")', "get_ipython().magic('html <h3>hallo</h3>')", 'get_ipython().magic(\'html print("<h1>Hallo</h1>")\')', 'get_ipython().magic(\'HTML <h1>Hallo

In [32]:
Out

{14: Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2 

In [36]:
In[34]

'In[1]'

# Out[5]

In [40]:
Out[1]

KeyError: 1

In [41]:
%magic


In [42]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%py

In [44]:
%run test.py

test


%echo hallo


In [47]:
%colors?


In [48]:
%ls?

In [49]:
%cd?

In [1]:
print in[9]

False

In [2]:
%time print("print helloworld")

print helloworld
Wall time: 0 ns


In [3]:
%prun?

In [4]:
%magic

In [5]:
import numpy as np

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np?

Object `np` not found.


In [9]:
np.ones((100,200), dtype=int)

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ..., 
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [12]:
np.random.seed?

In [19]:
np.random.seed(0)

x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))


print(x1)
print(x2)
print(x3)



[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [20]:
print(x3.ndim)

3


In [21]:
print(x2.ndim)
print(x1.shape)
print(x3.shape)
print(x3.size)

2
(6,)
(3, 4, 5)
60


In [22]:
x = np.array([[1,2,3,4,5,6],
             [7,8,9,10,11,12],
             [13,14,15,16,17,18]])
print(x)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [23]:
print(x[:,2])

[ 3  9 15]


In [24]:
print(x[1,:])

[ 7  8  9 10 11 12]


In [25]:
x_view = x[:2,:3]
x_copy = x[:2,:3].copy()
print(x_view)
print(x_copy)

x[0,0] = 500

print(x_view)
print(x_copy)



[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]
[[500   2   3]
 [  7   8   9]]
[[1 2 3]
 [7 8 9]]


In [28]:
np.arange?

In [30]:
np.arange(0,20).reshape((4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
y=np.array([1,2,3])
y

array([1, 2, 3])

In [32]:
y.reshape((1,3))

array([[1, 2, 3]])

In [2]:
import numpy as np

a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,5)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
c = np.concatenate([a,b])
d = np.concatenate([a,b], axis = 0)
e = np.concatenate([a,b], axis = 1)

print(c)
print(d)
print(e)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]


In [19]:
%%timeit
print(np.arange(10)/np.arange(1,11))
print(np.arange(10) - np.arange(1,11))

[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.833333

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  

[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.833333

[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.833333

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  

[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.833333

[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.833333

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  

[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.833333

[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0.          0.5         0.66666667  0.75        0.8         0.833333

In [21]:
print(np.arange(10)/np.arange(1,11))
print(np.arange(10) - np.arange(1,11))
print(np.arange(10) * np.arange(1,11))

[ 0.          0.5         0.66666667  0.75        0.8         0.83333333
  0.85714286  0.875       0.88888889  0.9       ]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0  2  6 12 20 30 42 56 72 90]


In [24]:
aap = np.empty(5)
np.empty?
print(aap)

[  4.24399158e-314   2.54639495e-313   6.36598737e-313   1.18831764e-312
   1.90979621e-312]


In [27]:
x = np.arange(5)
y = np.arange(5)
np.multiply(x, 10, out=y)
print(y)

[ 0 10 20 30 40]


In [31]:
x = np.arange(1,6)
y = np.add.reduce(x)
print(y)

15


In [32]:
a = np.arange(1,5)
b = np.arange(2,8)

c = np.multiply.outer(a,b)
print(c)

[[ 2  3  4  5  6  7]
 [ 4  6  8 10 12 14]
 [ 6  9 12 15 18 21]
 [ 8 12 16 20 24 28]]


In [35]:
L = np.random.random(100)
print(L)
print(np.sum(L))

[ 0.66312204  0.24309854  0.99657197  0.37810916  0.50031782  0.79134603
  0.51878099  0.83630874  0.4635882   0.05025661  0.53932923  0.05986379
  0.72491819  0.86937084  0.10404887  0.71679099  0.46164955  0.49554199
  0.02709417  0.31592678  0.45231078  0.13289512  0.54043978  0.43269964
  0.73380039  0.1217397   0.42665323  0.6807797   0.98624411  0.39733894
  0.4777071   0.58803518  0.13696782  0.13187139  0.9145875   0.30594194
  0.54184428  0.27873319  0.33086599  0.25809293  0.00807777  0.19237026
  0.69082294  0.36675533  0.59505902  0.77009325  0.54509906  0.13696714
  0.12394601  0.1373973   0.70878246  0.68544126  0.4332815   0.19524069
  0.85582758  0.6289623   0.31261545  0.75508848  0.05961545  0.7795985
  0.60867527  0.3694846   0.62246544  0.03233535  0.51535416  0.59186663
  0.89021848  0.07448545  0.65608041  0.0853397   0.51380994  0.05111736
  0.94451696  0.43424546  0.47401395  0.52045032  0.2854076   0.71556667
  0.2891015   0.2116972   0.31624886  0.61542071  0.

NameError: name 'piemel' is not defined

In [37]:
!head -4 data/president_height.csv

'head' is not recognized as an internal or external command,
operable program or batch file.


In [38]:
M = np.ones((1,3))

In [39]:
print(M)

[[ 1.  1.  1.]]


In [41]:
a = np.arange(50).reshape(5,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [42]:
print(x<10)

[ True  True  True  True  True]


In [43]:
x<10

array([ True,  True,  True,  True,  True], dtype=bool)

In [44]:
x<20

array([ True,  True,  True,  True,  True], dtype=bool)

In [45]:
x<2

array([ True, False, False, False, False], dtype=bool)

In [47]:
rng = np.random.RandomState(0)
x= rng.randint(10, size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [50]:
np.random.RandomState?

In [53]:
np.sum(x<6)
x<6


array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]], dtype=bool)

In [54]:
np.sum(x<6, axis =1)

array([4, 2, 2])

In [55]:
(x<6) & (x>3)

array([[ True, False, False, False],
       [False, False, False,  True],
       [False,  True, False, False]], dtype=bool)

In [56]:
np.bitwise_xor?

In [58]:
summer = (np.arange(365) - 172 <90) & (np.arange(365)-172 >0)
summer

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [12]:
import numpy as np
X = np.arange(12).reshape((3,4))

row = np.array([0,1,2])
new_row = row[:, np.newaxis]
print(new_row)
print(new_row[:, np.newaxis])

col = np.array([2,1,3])
X[row[:, np.newaxis], col]
print(X)

[[0]
 [1]
 [2]]
[[[0]]

 [[1]]

 [[2]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
X = np.arange(12).reshape(3,4)
print(X)
X[row[:, np.newaxis]]

mask = np.array([1,0,1,0], dtype = bool)
print(X[row, mask])

print(X[row[:, newaxis], mask])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [2]:
def linear(data, value):
	"""Return the index of 'value' in 'data', or -1 if it does not occur"""
	# Go through the data list from index 0 upwards
	i = 0
	# continue until value found or index outside valid range
	while i < len(data) and data[i] != value:
		# increase the index to go to the next data value
		i = i + 1
		if data[i] > value:
			i = len(data)
		
	# test if we have found the value
	if i == len(data):
		# no, we went outside valid range; return -1
		return 'does not occur'
	else:
		# yes, we found the value; return the index
		return i
		

#[1,2,3,4,4,6]

def binary(data,value):
	low = 0
	high = len(data)-1
	
	while (high - low) > 0 and data[low] != value:
		mid = int((high+low) / 2)
		print(mid)
	
		if data[mid] == value:
			low = mid
		elif value < data[mid]:
			high = mid-1
		else:
			low = mid+1
	if data[low] == value:
		return low
	else:
		return -1

def binary_pairs(data,value):
	low = 0
	high = len(data)-1
	
	while (high - low) > 0 and data[low][0] != value:
		mid = int((high+low) / 2)
		print(mid)
	
		if data[mid][0] == value:
			low = mid
		elif value < data[mid][0]:
			high = mid-1
		else:
			low = mid+1
	if data[low][0] == value:
		return low
	else:
		return -1
        
		return -1

In [ ]:
import util

#function that calls the sort and remove duplicate functions
def make_table(pairs):

	table = appendTxt(merge_pairs(pairs))
	return table

#function that sorts the pairs using merge sort	
def merge_pairs(data):
    if len(data) <= 1:
        return data
    else:
        half = int(len(data)/2)
        fst = merge_pairs(data[:half])
        snd = merge_pairs(data[half:])
        res = []
        fi,si = 0,0
        while fi < len(fst) and si < len(snd):
            if fst[fi][0] < snd[si][0] or fst[fi][0] == snd[si][0] and fst[fi][1] < snd[si][1]:
                res.append(fst[fi])
                fi += 1
            else:
                res.append(snd[si])
                si += 1
        if fi <= len(fst)-1:
            res.extend(fst[fi:])
        elif si <= len(snd)-1:
            res.extend(snd[si:])
        return res