In [5]:
import numpy as np

In [13]:
# creating arrays in numPy
a = np.array([11,23,415,25,2143])
b = np.arange(20)

np.random.seed(0)
c = np.random.randint(10, size = (3,4))

print(a)
print(b)
print(c)

print(c.ndim)
print(c.shape)
print(c.size)

[  11   23  415   25 2143]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
2
(3, 4)
12


In [24]:
# slicing
# x[start:stop:step]
print(b[5:])
print(b[8:17])

# copy arrays
b1 = b[5:].copy()
print(b1)

# reshaping arrays
grid = np.arange(1, 10).reshape((3,3))
print(grid)

grid2 = np.array([1,2,3])
print(grid2)
print(grid2.reshape((3,1)))
print(grid2.reshape((1,3)))
print(grid2[np.newaxis, :])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 8  9 10 11 12 13 14 15 16]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]
[[1 2 3]]


In [41]:
# concatenation and splitting
x = np.arange(3)
y = np.arange(3)
print(np.concatenate([x,y]))

grid = np.array([[1,2,3], [1,2,3]])

print(np.concatenate([grid, grid], axis = 1))
print(np.vstack([grid,grid]))
print(np.hstack([grid,grid]))

x = np.arange(10)
y = np.split(x, [2,5])
print(y)

p = np.arange(16)
q = p.reshape([4,4])
print(q)

upper, lower = np.vsplit(q, [2])
print(upper)
print(lower)
left, right = np.hsplit(q, [2])
print(left)
print(right)

[0 1 2 0 1 2]
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]]
[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [50]:
# Universal functions (Ufuncs)
x = np.arange(9).reshape([3,3])
print(x)
print(x**2)
print(np.sin(x))

# aggregates
y = np.arange(20)
print(np.add.reduce(y))
print(np.multiply.reduce(y[1:]))
print(np.add.accumulate(y))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825]]
190
109641728
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]


In [55]:
# broadcasting: apply ufucts on arrays of different sizes
# rule 1: if the two arrays differ in their number of dimentsions, 
# the shape of the one with fewer dimensions is padded with ones on it leading (left) size

# rule 2: if the shape of the two arrays does not match in any dimension,
# the array with shape equal to 1 in that dimension is stretched to match the other shape

# rule 3: if in any dimension the sizes disagree and neither is is equal to 1, an error is rased
a = np.array([0,1,2])
b = np.array([2,1,0])
print(a+b)
print(a-b)

c = np.ones([3,3])
d = np.arange(3)
print(c+d)

[2 2 2]
[-2  0  2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [60]:
# masks
x = np.arange(20)
print(x)
c = x%2 == 0
print(c)
print(x[c])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
[ 0  2  4  6  8 10 12 14 16 18]


In [70]:
# fancy indexing
x = np.array([1,2,45,12,34,1523,31,23,3])
y = np.array([0,4,5])
print(x[y])

# combined indexing
x = np.arange(12).reshape([3,4])
print(x)
print(x[2, [2,0,1]])
print(x[1:, [2,0,1]])
mask = np.array([1,0,1,0], dtype=bool)
row = np.arange(3)
print(x[row[:, np.newaxis], mask])

# linspace
z = np.linspace(0, 100, 20)
print(z)
/


[   1   34 1523]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[10  8  9]
[[ 6  4  5]
 [10  8  9]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
